spring:
  application:
    name: acehq
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:acehq}_dev"
    username: "${DATABASE_USERNAME:postgres}"
    password: "${DATABASE_PASSWORD:postgres}"
app:
  frontend-url: "${FRONTEND_URL:http://localhost:3000}"
  frontend-host: "${FRONTEND_HOST:localhost:3000}"
  backend-host: "${BACKEND_HOST:localhost:8080}"
clerk:
  secret: "${CLERK_SECRET_KEY}"
  authorized-party: "${CLERK_AUTHORIZED_PARTY:#{'http://localhost:3000'}}"
  jwt-encoded: "${CLERK_JWT_ENCODED}"